import type { Metadata } from "next";
import "./globals.css";
import CircleCursor from "./(components)/CircleCursor";
import Nav from "./(components)/Nav";
import CursorShadow from "./(components)/CursorShadow";

import { Maven_Pro } from "next/font/google";

const maven = Maven_Pro({
  subsets: ["latin"],
  variable: "--font-maven",
});

export const metadata: Metadata = {
  title: "ItsMushfik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CircleCursor />
        <div className={"body font-sans " + maven.variable}>
          {/* <Nav /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
