import type { Metadata } from "next";
import { useState } from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";
import CursorShadow from "./(components)/CursorShadow";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ItsMushfik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CursorShadow>
          <div className="body">
            <Nav />
            {children}
          </div>
        </CursorShadow>
      </body>
    </html>
  );
}
